import java.util.Scanner;

public class ExceptionProblems {

	
	public static int divide(int a , int b)
	{
	
		return a/b;
		
	}
	
//	public static void main(String[] args)
//	{
//		System.out.print("Enter first value");
//		System.out.print("\n");
//		Scanner sc = new Scanner(System.in);
//		int a = sc.nextInt();
//		System.out.print("Enter second value");
//		System.out.print("\n");
//		int b = sc.nextInt();
//		
//		try {
//			System.out.print("\n");
//			int ans = divide(a,b);
//			System.out.print("Ans:"+ans);
//		} catch (Exception e) {
//			System.out.print("\n");
//			System.out.print("exception has been caught, please provide valid input. ");
//			e.printStackTrace();
//		}
//		finally{
//			System.out.print("\n");
//			System.out.print("operation has been completed");
//		}
//		
//	}
}
